### ISSUE TITLE
Lobechat running in local network

### ISSUE THREAD

**Issue by githubdebugger** [moreoronce/LobeChat-Android#2]
I have lobechat running in local network, lets say on 10.1.1.1:3210 and when I try to connect to http://10.1.1.1:3210/chat by entering in the URL on LobeChat-Android app, it errors out saying "Enter a valid URL/address". I tried to enter https://lobechat.com/chat in the same and that works, however, if you are running lobechat locally it fails.

Could you please fix it such that the app is able to accept address/URL which is locally (any IP address 10.x.x.x 192.168.x.x) + not hosted on https (insecure, as they are locally hosted).

Thanks!

**Comment by moreoronce** [comment]
fixed

**Comment by githubdebugger** [comment]
Thank you so much! Let me check this out.

**Comment by githubdebugger** [comment]
Now. in the latest version 0.0.5, I am able to connect to lobechat server running locally on http://10.1.1.1:3210/chat (that issue is fixed/resolved where it was throwing error on the URL itself, now it says "Lobechat Validation passed"), however, it seems like when I try to login with already created username and password, by clicking on Me (on the bottom right corner), after I enter the username and password, instead of logging me in, it goes back to "Me" page, where it still shows the option for login/signup, instead of showing the logged in username.

When I do this on a browser, everything works fine, smoothly. Without any issues.

Do you see the above issue as well?

**Comment by moreoronce** [comment]
> Now. in the latest version 0.0.5, I am able to connect to lobechat server running locally on http://10.1.1.1:3210/chat (that issue is fixed/resolved where it was throwing error on the URL itself, now it says "Lobechat Validation passed"), however, it seems like when I try to login with already created username and password, by clicking on Me (on the bottom right corner), after I enter the username and password, instead of logging me in, it goes back to "Me" page, where it still shows the option for login/signup, instead of showing the logged in username.
> 
> When I do this on a browser, everything works fine, smoothly. Without any issues.
> 
> Do you see the above issue as well?

Did you run the Lobechat Server locally in a Docker container?

**Comment by githubdebugger** [comment]
> > Now. in the latest version 0.0.5, I am able to connect to lobechat server running locally on http://10.1.1.1:3210/chat (that issue is fixed/resolved where it was throwing error on the URL itself, now it says "Lobechat Validation passed"), however, it seems like when I try to login with already created username and password, by clicking on Me (on the bottom right corner), after I enter the username and password, instead of logging me in, it goes back to "Me" page, where it still shows the option for login/signup, instead of showing the logged in username.
> > When I do this on a browser, everything works fine, smoothly. Without any issues.
> > Do you see the above issue as well?
> 
> Did you run the Lobechat Server locally in a Docker container?

I have modified official lobechat docker files such that, you can access it locally or from another host locally via IP address. If you have docker installed, you can easily try this out, this is the repo: https://github.com/githubdebugger/lobechat_server

Steps:

1. Clone the repo to a folder.
2. cd into the folder, and run ./setup.sh
3. Copy .env.example to .env
4. Set HOST_IP to the address where you would be running this server on, in this .env file
5. API_KEY's are optional to test with your android app
6. Replace IP Address to your IP address in two locations in init_data.json file:
homepageUrl: http://<YOUR_HOST_IP>:3210
redirectUris: http://<YOUR_HOST_IP>:3210/api/auth/callback/casdoor

Finally:

docker compose up -d

Now you can go to the server if locally on http://localhost:3210/ or with the IP address or anywhere on your local address with http://<ip_address>:3210

You will be able to create username and password and login with the same and then try the same with the your lobechat-android app, which can open the server, but, unable to login.

I hope this helps.
